//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.0 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2023.12.20 at 02:10:09 PM IST 
//


package com.geography.countries;

import jakarta.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.geography.countries package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.geography.countries
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link CountryCultureRequest }
     * 
     */
    public CountryCultureRequest createCountryCultureRequest() {
        return new CountryCultureRequest();
    }

    /**
     * Create an instance of {@link Culture }
     * 
     */
    public Culture createCulture() {
        return new Culture();
    }

    /**
     * Create an instance of {@link CountryGKRequest }
     * 
     */
    public CountryGKRequest createCountryGKRequest() {
        return new CountryGKRequest();
    }

    /**
     * Create an instance of {@link GK }
     * 
     */
    public GK createGK() {
        return new GK();
    }

}
