//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.0 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2023.12.15 at 02:48:18 PM IST 
//

@jakarta.xml.bind.annotation.XmlSchema(namespace = "http://www.ws.com/soap/loaneligibility", elementFormDefault = jakarta.xml.bind.annotation.XmlNsForm.QUALIFIED)
package com.ws.soap.loaneligibility;
